version: '3'
services:
  backend:
    container_name: backend-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: 'mongo:4'
    ports:
      - 27017:27017
